Add cereal to the run dependencies in meta.yaml
Otherwise, the error occurs:

```
LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides cereal needed by iowarp-core-0.1.0-py312h3fd9d12_0
Could not solve for environment specs
The following package could not be installed
└─ iowarp-core =* * is not installable because it requires
   └─ cereal =* *, which does not exist (perhaps a missing channel).
```